// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPPZSkgHeRr3CWH2NNTSPfcatIRYBIOCQ',
    appId: '1:70967452184:web:e98a9b29139f240b7a596d',
    messagingSenderId: '70967452184',
    projectId: 'instagram-clone-c2626',
    authDomain: 'instagram-clone-c2626.firebaseapp.com',
    storageBucket: 'instagram-clone-c2626.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3NTrPJxBjP52CVgIoXy_KjcLYwR8pe2E',
    appId: '1:70967452184:android:96b29a4a2bce0a487a596d',
    messagingSenderId: '70967452184',
    projectId: 'instagram-clone-c2626',
    storageBucket: 'instagram-clone-c2626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnyw159vgY2t49dGkKnGA5L-1rjyZn7XU',
    appId: '1:70967452184:ios:9af7771f105b9b9e7a596d',
    messagingSenderId: '70967452184',
    projectId: 'instagram-clone-c2626',
    storageBucket: 'instagram-clone-c2626.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnyw159vgY2t49dGkKnGA5L-1rjyZn7XU',
    appId: '1:70967452184:ios:32da0d5edd01d29d7a596d',
    messagingSenderId: '70967452184',
    projectId: 'instagram-clone-c2626',
    storageBucket: 'instagram-clone-c2626.appspot.com',
    iosBundleId: 'com.example.chatty.RunnerTests',
  );
}
